### ISSUE TITLE
Ler é Preciso

### ISSUE THREAD

**Issue by SGoldMiner** [DivulgacaoCientifica/divulgacaocientifica#10]
## Qual o nome do PodCast/Youtube/Blog você deseja adicionar?
Ler é Preciso
## Qual é a área de conhecimento?
Literatura
## Qual é o link para o conteúdo?
https://www.youtube.com/channel/UCEesnwWJEaUVb9bRplq_CNQ
## Alguma outra observação.

**Comment by brilvio** [comment]
Obrigado pela contribuição, foi adicionado na lista.
