### ISSUE TITLE
Inclusão

### ISSUE THREAD

**Issue by mileneaae** [DivulgacaoCientifica/divulgacaocientifica#12]
Oi pessoal,

Vocês podem incluir meus canais de divulgação científica em Ecologia? Instagram - @eco.et.al e Facebook - https://www.facebook.com/milene.ecoetal/

Obrigada!

**Comment by brilvio** [comment]
Olá como não temos um espaço somente para facebook coloquei os dois links em https://github.com/DivulgacaoCientifica/divulgacaocientifica/blob/master/INSTAGRAM.md

Obrigado pela contribuição.
