### ISSUE TITLE
Atualizar lista

### ISSUE THREAD

**Issue by lauramaoliveira** [DivulgacaoCientifica/divulgacaocientifica#13]
Gostaria de adicionar o instagram de Comunicação e divulgação científica DivulgaMicro a lista.

**Comment by francyne-ep** [comment]
Gostaria de adicionar meu instagram de divulgaçao científica da Antártica e dos Oceanos. @gelonabagagem
Obrigada

**Comment by jovemadulto** [comment]
Perfis incluídos. Obrigado pela contribuição de ambas! :D
