### ISSUE TITLE
Bruno Sapiência 

### ISSUE THREAD

**Issue by BrunoDoSapiencia** [DivulgacaoCientifica/divulgacaocientifica#3]
Possuo um canal de divulgação científica chamado Canal Sapiência voltado para a área de Biologia, gostaria que ele fosse incluido na lista!!! Muito obrigado, vocês estão fazendo um trabalho espetacular 💙

**Comment by jovemadulto** [comment]
Você pode mandar o link pra gente, pra não ter erro de adicionar o canal errado?

**Comment by BrunoDoSapiencia** [comment]
Claro!!! https://www.youtube.com/channel/UChMzLbUCqjArXce-IspNa8Q é esse aqui ó!! Muito obrigado!!

**Comment by brilvio** [comment]
Adicionado, Obrigado pela contribuição.
