### ISSUE TITLE
Viver Ciência

### ISSUE THREAD

**Issue by rtve-tvufg** [DivulgacaoCientifica/divulgacaocientifica#4]
Olá! Não sabemos atualizar a lista e para não correr o risco de fazer algo errado, preferimos mandar nossa sugestão por aqui! Abraços!

Sugestão para a lista: 
Nome: Viver Ciência
Área do Conhecimento: Ciência e Educação
Endereço: www.youtube.com/tvufg

**Comment by jovemadulto** [comment]
Canal adicionado. Muito obrigado!
