### ISSUE TITLE
Tudo é Física

### ISSUE THREAD

**Issue by SGoldMiner** [DivulgacaoCientifica/divulgacaocientifica#8]
## Qual o nome do PodCast/Youtube/Blog você deseja adicionar?
Tudo é Física
## Qual é a área de conhecimento?
Física
## Qual é o link para o conteúdo?
https://www.youtube.com/channel/UCUwc8Mchmm82TNLutPUOkNA
# Alguma outra observação.

**Comment by brilvio** [comment]
Obrigado pela contribuição, foi adicionado na lista.
