### ISSUE TITLE
Super Exatas

### ISSUE THREAD

**Issue by SGoldMiner** [DivulgacaoCientifica/divulgacaocientifica#9]
## Qual o nome do PodCast/Youtube/Blog você deseja adicionar?
Super Exatas
## Qual é a área de conhecimento?
Ciências Exatas
## Qual é o link para o conteúdo?
https://www.youtube.com/channel/UCj-kGcLi7TsB4HXw4BqkvGw

**Comment by brilvio** [comment]
Obrigado pela contribuição, foi adicionado na lista.
